// All Headers : Table
export const allHeaders = {
  ID: "id",
  "First Name": "firstName",
  "Last Name": "lastName",
  "Middle Name": "middleName",
  "Mobile Number": "mobileNo",
  Birthdate: "birthdate",
  "Aadhar Card": "adharcard",
  Pancard: "pancard",
  EmailID: "emailId",
  Address: "address",
  Village: "village",
  Post: "post",
  Pincode: "pincode",
  Taluka: "taluka",
  District: "district",
  State: "state",
  "Bank Name": "bankName",
  "Account Number": "accountNo",
  Business: "buisiness",
  "Other Service Post": "otherServicePost",
  "Political Party": "politicalParty",
  Sanghtana: "sanghtana",
  Supporter: "supporter",
  "Voting Number": "votingNo",
  "Ward Number": "wardNo",
  Booth: "booth",
  "Created At": "createdAt",
  "Created By": "createdBy",
  "Updated At": "updatedAt",
  "Updated By": "updatedBy",
};
// Default Selected Headers : Table
export const defaultHeaders = {
  Action: "action",
  ID: "id",
  "First Name": "firstName",
  "Middle Name": "middleName",
  "Last Name": "lastName",
  Address: "address",
  Pancard: "pancard",
  "Aadhar Card": "adharcard",
  "Mobile Number": "mobileNo",
  Birthdate: "birthdate",
};
