// Fetch customer list data
export const GET_CUSTOMER_DATA = "GET_CUSTOMER_DATA";
export const GET_CUSTOMER_DATA_SUCCESS = "GET_CUSTOMER_DATA_SUCCESS";
export const GET_CUSTOMER_DATA_FAIL = "GET_CUSTOMER_DATA_FAIL";

// Add/Edit customer data
export const ADD_EDIT_CUSTOMER = "ADD_EDIT_CUSTOMER";
export const ADD_EDIT_CUSTOMER_SUCCESS = "ADD_EDIT_CUSTOMER_SUCCESS";
export const ADD_EDIT_CUSTOMER_FAIL = "ADD_EDIT_CUSTOMER_FAIL";

// Delete customer
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAIL = "DELETE_CUSTOMER_FAIL";

// Reset
export const RESET_ADD_EDIT_DELETE_CUSTOMER = "RESET_ADD_EDIT_DELETE_CUSTOMER";
