// Fetch service list data
export const GET_SERVICE_DATA = "GET_SERVICE_DATA";
export const GET_SERVICE_DATA_SUCCESS = "GET_SERVICE_DATA_SUCCESS";
export const GET_SERVICE_DATA_FAIL = "GET_SERVICE_DATA_FAIL";

// Add/Edit service data
export const ADD_EDIT_SERVICE = "ADD_EDIT_SERVICE";
export const ADD_EDIT_SERVICE_SUCCESS = "ADD_EDIT_SERVICE_SUCCESS";
export const ADD_EDIT_SERVICE_FAIL = "ADD_EDIT_SERVICE_FAIL";

// Delete service
export const DELETE_SERVICE = "DELETE_SERVICE";
export const DELETE_SERVICE_SUCCESS = "DELETE_SERVICE_SUCCESS";
export const DELETE_SERVICE_FAIL = "DELETE_SERVICE_FAIL";
